const videosData = [
    {
        "id":  "yJoCLFZ8Q9k",
        "title":  "Skull Tales - Unboxing - Juego de mesa",
        "version":  "Skull Tales",
        "type":  "Componentes y Unboxing",
        "year":  "2016",
        "lang":  "Español",
        "duration":  "9:05",
        "author":  "¡Jugad, insensatos!"
    },
    {
        "id":  "Cmc8hOEueMs",
        "title":  "Desprecintando Deluxe – Skull Tales (4k-unboxing)",
        "version":  "Skull Tales",
        "type":  "Componentes y Unboxing",
        "year":  "2016",
        "lang":  "Español",
        "duration":  "14:59",
        "author":  "Análisis Parálisis"
    },
    {
        "id":  "yZlETrcb7QE",
        "title":  "Skull Tales unboxing / desprecintando juego de mesa español",
        "version":  "Skull Tales",
        "type":  "Componentes y Unboxing",
        "year":  "2016",
        "lang":  "Español",
        "duration":  "12:02",
        "author":  "Hardhead´s Reviews"
    },
    {
        "id":  "1InTbAOZdy8",
        "title":  "Unboxing ninja Skull Tales juego de mesa español",
        "version":  "Skull Tales",
        "type":  "Componentes y Unboxing",
        "year":  "2016",
        "lang":  "Español",
        "duration":  "4:45",
        "author":  "Hardhead´s Reviews"
    },
    {
        "id":  "2L7IVj1ZuUA",
        "title":  "Unboxing – Skull Tales",
        "version":  "Skull Tales",
        "type":  "Componentes y Unboxing",
        "year":  "2016",
        "lang":  "Español",
        "duration":  "27:01",
        "author":  "SensaJuegos"
    },
    {
        "id":  "nwy1KDK2Zjo",
        "title":  "Skull Tales – Unboxing",
        "version":  "Skull Tales",
        "type":  "Componentes y Unboxing",
        "year":  "2017",
        "lang":  "Español",
        "duration":  "44:22",
        "author":  "Discípulos de Armitage"
    },
    {
        "id":  "VarAKEufnbo",
        "title":  "Skull Tales – ¿Qué lleva dentro?",
        "version":  "Skull Tales",
        "type":  "Componentes y Unboxing",
        "year":  "2017",
        "lang":  "Español",
        "duration":  "9:53",
        "author":  "Meepletopía"
    },
    {
        "id":  "CBR0VsRnE70",
        "title":  "Skull Tales Promo",
        "version":  "Skull Tales",
        "type":  "Crowdfunding, Trailers y Campañas",
        "year":  "2015",
        "lang":  "Español",
        "duration":  "1:59",
        "author":  "The Radikal Games"
    },
    {
        "id":  "IVF48PNsJz8",
        "title":  "Skull Tales Promo",
        "version":  "Skull Tales",
        "type":  "Crowdfunding, Trailers y Campañas",
        "year":  "2015",
        "lang":  "Francés",
        "duration":  "2:41",
        "author":  "The Radikal Games"
    },
    {
        "id":  "Qk9RA1nbn0c",
        "title":  "Skull Tales partida rápida – Gameplay juego de mesa español",
        "version":  "Skull Tales",
        "type":  "Gameplay (Aventura)",
        "year":  "2016",
        "lang":  "Español",
        "duration":  "12:43",
        "author":  "Hardhead´s Reviews"
    },
    {
        "id":  "qphAe8LYVuI",
        "title":  "Skull Tales – Partida – El secreto del capitán Jones (aventuras)",
        "version":  "Skull Tales",
        "type":  "Gameplay (Aventura)",
        "year":  "2017",
        "lang":  "Español",
        "duration":  "1:39:05",
        "author":  "Discípulos de Armitage"
    },
    {
        "id":  "0zLYqSdka3s",
        "title":  "Skull Tales – Partida – Naufragio",
        "version":  "Skull Tales",
        "type":  "Gameplay (Aventura)",
        "year":  "2017",
        "lang":  "Español",
        "duration":  "1:47:43",
        "author":  "Discípulos de Armitage"
    },
    {
        "id":  "oh1oT0BNGOk",
        "title":  "Skull Tales Promo Adventure Gameplay",
        "version":  "Skull Tales",
        "type":  "Gameplay (Aventura)",
        "year":  "2015",
        "lang":  "Inglés",
        "duration":  "1:08:18",
        "author":  "The Radikal Games"
    },
    {
        "id":  "VP6lpXFSGHE",
        "title":  "Skull Tales review – Cómo se juega juego de mesa español",
        "version":  "Skull Tales",
        "type":  "Gameplay (Capítulo)",
        "year":  "2016",
        "lang":  "Español",
        "duration":  "24:11",
        "author":  "Hardhead´s Reviews"
    },
    {
        "id":  "0s1K-JFPzeA",
        "title":  "Skull Tales – Partida – El despertar de la oscuridad",
        "version":  "Skull Tales",
        "type":  "Gameplay (Capítulo)",
        "year":  "2017",
        "lang":  "Español",
        "duration":  "2:51:26",
        "author":  "Discípulos de Armitage"
    },
    {
        "id":  "ikbjd-FDys4",
        "title":  "Skull Tales – Partida – El exilio",
        "version":  "Skull Tales",
        "type":  "Gameplay (Capítulo)",
        "year":  "2017",
        "lang":  "Español",
        "duration":  "2:40:40",
        "author":  "Discípulos de Armitage"
    },
    {
        "id":  "hVnAvsXvoIE",
        "title":  "Skull Tales partida rápida Fase de Travesía",
        "version":  "Skull Tales",
        "type":  "Gameplay (Travesía)",
        "year":  "2016",
        "lang":  "Español",
        "duration":  "15:25",
        "author":  "Hardhead´s Reviews"
    },
    {
        "id":  "fIWVawDXYQ0",
        "title":  "Skull Tales – Partida – El secreto del capitán Jones (travesía)",
        "version":  "Skull Tales",
        "type":  "Gameplay (Travesía)",
        "year":  "2017",
        "lang":  "Español",
        "duration":  "58:52",
        "author":  "Discípulos de Armitage"
    },
    {
        "id":  "3u6TYGSmJgA",
        "title":  "Juego de mesa Skull Tales – Información exclusiva + presentación",
        "version":  "Skull Tales",
        "type":  "Presentaciones y entrevistas",
        "year":  "2014",
        "lang":  "Español",
        "duration":  "13:23",
        "author":  "Hardhead´s Reviews"
    },
    {
        "id":  "WorGLtquw6Q",
        "title":  "MagTV – Skull Tales",
        "version":  "Skull Tales",
        "type":  "Presentaciones y entrevistas",
        "year":  "2015",
        "lang":  "Español",
        "duration":  "36:04",
        "author":  "5 Minutos por juego"
    },
    {
        "id":  "OvX06FWoN0s",
        "title":  "Presentación Skull Tales",
        "version":  "Skull Tales",
        "type":  "Presentaciones y entrevistas",
        "year":  "2015",
        "lang":  "Español",
        "duration":  "36:36",
        "author":  "Análisis Parálisis"
    },
    {
        "id":  "9viaBOS5mA8",
        "title":  "Skull Tales opinión y conclusión juego de mesa español",
        "version":  "Skull Tales",
        "type":  "Reseñas y opiniones",
        "year":  "2016",
        "lang":  "Español",
        "duration":  "7:57",
        "author":  "Hardhead´s Reviews"
    },
    {
        "id":  "VXkZCR9Ih9Y",
        "title":  "PreReseña – Skull Tales",
        "version":  "Skull Tales",
        "type":  "Reseñas y opiniones",
        "year":  "2016",
        "lang":  "Español",
        "duration":  "5:07",
        "author":  "SensaJuegos"
    },
    {
        "id":  "CxthEXdf0jE",
        "title":  "Conociendo Skull Tales",
        "version":  "Skull Tales",
        "type":  "Reseñas y opiniones",
        "year":  "2016",
        "lang":  "Español",
        "duration":  "14:02",
        "author":  "Zacatrus"
    },
    {
        "id":  "F143YxKoMXE",
        "title":  "Skull Tales – Reseña – Opinión",
        "version":  "Skull Tales",
        "type":  "Reseñas y opiniones",
        "year":  "2017",
        "lang":  "Español",
        "duration":  "14:58",
        "author":  "Discípulos de Armitage"
    },
    {
        "id":  "TXT16hsx_MU",
        "title":  "Skull Tales Overview and Review",
        "version":  "Skull Tales",
        "type":  "Reseñas y opiniones",
        "year":  "2015",
        "lang":  "Inglés",
        "duration":  "20:09",
        "author":  "Funattic Channel"
    },
    {
        "id":  "vOW2Pqd2uTo",
        "title":  "Unboxing: Skull Tales Full Sail! (deutsch/german)",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Componentes y Unboxing",
        "year":  "2020",
        "lang":  "Alemán",
        "duration":  "18:45",
        "author":  "Mr. Flexx"
    },
    {
        "id":  "X-2pN41Dhb8",
        "title":  "Skull Tales ¡A toda vela!, Unboxing Megaexpansión",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Componentes y Unboxing",
        "year":  "2019",
        "lang":  "Español",
        "duration":  "8:12",
        "author":  "Cool Games"
    },
    {
        "id":  "QlYgU8rDoJ8",
        "title":  "Skull Tales ¡A toda vela!, Unboxing en español",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Componentes y Unboxing",
        "year":  "2019",
        "lang":  "Español",
        "duration":  "7:31",
        "author":  "Cool Games"
    },
    {
        "id":  "rvxKtB5ywxY",
        "title":  "Skull Tales ¡A toda vela!. Unboxing",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Componentes y Unboxing",
        "year":  "2019",
        "lang":  "Español",
        "duration":  "55:30",
        "author":  "Discípulos de Armitage"
    },
    {
        "id":  "jTPJmFMgBkY",
        "title":  "Unboxing Skull Tales 2ª Edición - Versión Kickstarter",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Componentes y Unboxing",
        "year":  "2019",
        "lang":  "Español",
        "duration":  "13:15",
        "author":  "El Rincón del Meeple"
    },
    {
        "id":  "NlNZ94rrUjo",
        "title":  "Skull Tales v2 – Unboxing – desprecintando",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Componentes y Unboxing",
        "year":  "2019",
        "lang":  "Español",
        "duration":  "17:24",
        "author":  "Hardhead´s Reviews"
    },
    {
        "id":  "TX-EnpIP6do",
        "title":  "Megaunboxing de Skull Tales – Directo - ¿Qué lleva dentro?",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Componentes y Unboxing",
        "year":  "2019",
        "lang":  "Español",
        "duration":  "1:12:19",
        "author":  "Meepletopía"
    },
    {
        "id":  "LYpcoGqRGqE",
        "title":  "Skull tales a toda vela. Miniaturas. ¿Polémica? Gñé",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Componentes y Unboxing",
        "year":  "2019",
        "lang":  "Español",
        "duration":  "24:04",
        "author":  "Ridlixcot linguafoeda acheronsis"
    },
    {
        "id":  "FQra2KqVy30",
        "title":  "Skull Tales – Contenido (1ª Edición)",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Componentes y Unboxing",
        "year":  "2019",
        "lang":  "Español",
        "duration":  "2:37",
        "author":  "Sulker"
    },
    {
        "id":  "WhxeLtM5wwY",
        "title":  "Skull Tales – Componentes (Tutorial 04)",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Componentes y Unboxing",
        "year":  "2019",
        "lang":  "Español",
        "duration":  "13:27",
        "author":  "Yo tenía un juego"
    },
    {
        "id":  "jq1z3vFWw_A",
        "title":  "Skull Tales – Unboxing ¡A Toda Vela! – All in",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Componentes y Unboxing",
        "year":  "2019",
        "lang":  "Español",
        "duration":  "20:40",
        "author":  "Yo tenía un juego"
    },
    {
        "id":  "sgQNa7eUKYA",
        "title":  "Lista de reproducción Skull Tales (Personajes, Aliados, Enemigos, Losetas, Cartas, Otros Componentes)",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Componentes y Unboxing",
        "year":  "2021",
        "lang":  "Español",
        "duration":  "10:36",
        "author":  "Mi juego del mes"
    },
    {
        "id":  "vC2Sf79FkNs",
        "title":  "Skull Tales Tortuga – Tutorial, novedades, de qué va y Unboxing expansión gamefound",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Componentes y Unboxing",
        "year":  "2021",
        "lang":  "Español",
        "duration":  "5:24",
        "author":  "Yo tenía un juego"
    },
    {
        "id":  "xZ8i7Y09PSI",
        "title":  "Skull Tales Full Sail Mega Expansion - Unboxing \u0026 Impressions",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Componentes y Unboxing",
        "year":  "2019",
        "lang":  "Ingles",
        "duration":  "18:47",
        "author":  "Epitrapaizoume"
    },
    {
        "id":  "2KW-MdsXx5o",
        "title":  "Dice Tower – Skull Tales – Kickstarter 2018",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Componentes y Unboxing",
        "year":  "2018",
        "lang":  "Inglés",
        "duration":  "0:27",
        "author":  "¡Jugad, insensatos!"
    },
    {
        "id":  "yoaOD5R0CNw",
        "title":  "Skull Tales: Full Sail + Mega Expansion + Add-Ons unboxing with Pirates!",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Componentes y Unboxing",
        "year":  "2019",
        "lang":  "Inglés",
        "duration":  "20:20",
        "author":  "Pirate’s Parley Gaming!"
    },
    {
        "id":  "fVDLoUBhK_E",
        "title":  "Unboxing Skull Tales: Full Sail Mega-Expansion",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Componentes y Unboxing",
        "year":  "2019",
        "lang":  "Inglés",
        "duration":  "22:04",
        "author":  "Soloed Quest"
    },
    {
        "id":  "CwGDxRXqBkE",
        "title":  "Skull Tales: 12 doors",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Componentes y Unboxing",
        "year":  "2018",
        "lang":  "No",
        "duration":  "0:05",
        "author":  "Draco Ideas"
    },
    {
        "id":  "ExME2hxqudQ",
        "title":  "Skull Tales: 5 chest",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Componentes y Unboxing",
        "year":  "2018",
        "lang":  "No",
        "duration":  "0:05",
        "author":  "Draco Ideas"
    },
    {
        "id":  "2kJFCQrkOr8",
        "title":  "Skull Tales: Plastic Coins – Monedas de Plástico",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Componentes y Unboxing",
        "year":  "2018",
        "lang":  "No",
        "duration":  "0:06",
        "author":  "Draco Ideas"
    },
    {
        "id":  "gsB0vNFyX4M",
        "title":  "Dials \u0026 Rivets / Diales y Ejes",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Componentes y Unboxing",
        "year":  "2019",
        "lang":  "No",
        "duration":  "1:23",
        "author":  "Draco Ideas"
    },
    {
        "id":  "LbDqz_yQmHM",
        "title":  "Mini-unboxing Skull Tales Core (juego base)",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Componentes y Unboxing",
        "year":  "2019",
        "lang":  "No",
        "duration":  "1:59",
        "author":  "Draco Ideas"
    },
    {
        "id":  "VYW__9B34FM",
        "title":  "Mini-unboxing Skull Tales Mega Expansión",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Componentes y Unboxing",
        "year":  "2019",
        "lang":  "No",
        "duration":  "2:45",
        "author":  "Draco Ideas"
    },
    {
        "id":  "YJGWOnwelro",
        "title":  "Skull Tales: mini boxes (mini cajas)",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Componentes y Unboxing",
        "year":  "2019",
        "lang":  "No",
        "duration":  "2:07",
        "author":  "Draco Ideas"
    },
    {
        "id":  "0kV4LKwEYLQ",
        "title":  "Skull Tales – Unboxing",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Componentes y Unboxing",
        "year":  "2019",
        "lang":  "No",
        "duration":  "2:10",
        "author":  "Meffy Games"
    },
    {
        "id":  "XsJ-hSvO9rI",
        "title":  "Skull Tales Megaexpansion – Unboxing",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Componentes y Unboxing",
        "year":  "2019",
        "lang":  "No",
        "duration":  "1:00",
        "author":  "Meffy Games"
    },
    {
        "id":  "nGvzd8E6KhI",
        "title":  "Skull Tales Full Sail - All Miniatures (todas las miniaturas)",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Componentes y Unboxing",
        "year":  "2020",
        "lang":  "No",
        "duration":  "4:40",
        "author":  "Mr. Flexx"
    },
    {
        "id":  "UdAY1IlY8_Y",
        "title":  "Trailer “Skull Tales: ¡A Toda Vela!” Kickstarter",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Crowdfunding, Trailers y Campañas",
        "year":  "2018",
        "lang":  "Español",
        "duration":  "3:59",
        "author":  "Sulker"
    },
    {
        "id":  "KcxekI2OHww",
        "title":  "Trailer “Skull Tales: ¡A Toda Vela!” Kickstarter",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Crowdfunding, Trailers y Campañas",
        "year":  "2018",
        "lang":  "Inglés",
        "duration":  "3:59",
        "author":  "Sulker"
    },
    {
        "id":  "GRdKCjAPOh0",
        "title":  "Skull Tales: Full Sail! - Regel \u0026 Playthrough - Kampagne 1 Kapitel 1 - Adventure-Phase – deutsch",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Gameplay (Aventura)",
        "year":  "2019",
        "lang":  "Alemán",
        "duration":  "3:04:19",
        "author":  "Mr. Flexx"
    },
    {
        "id":  "96G9uc_wbNY",
        "title":  "Skull Tales (Full Sail – A toda vela) – Presentación y Partida Campaña 1",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Gameplay (Aventura)",
        "year":  "2018",
        "lang":  "Español",
        "duration":  "1:24:45",
        "author":  "JueGorrinos"
    },
    {
        "id":  "MAXgQvrG5X0",
        "title":  "Skull Tales 2.0 (a toda vela): así lo jugamos",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Gameplay (Aventura)",
        "year":  "2018",
        "lang":  "Español",
        "duration":  "1:39:21",
        "author":  "La Mazmorra de Pacheco"
    },
    {
        "id":  "EQcCi-NIwVI",
        "title":  "Skull Tales ¡A toda vela! Partida - Fase de Aventura",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Gameplay (Aventura)",
        "year":  "2019",
        "lang":  "Español",
        "duration":  "2:27:23",
        "author":  "Discípulos de Armitage"
    },
    {
        "id":  "PIR2njwB2wA",
        "title":  "Lista de reproducción Skull Tales (Ejemplo Aventura)",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Gameplay (Aventura)",
        "year":  "2021",
        "lang":  "Español",
        "duration":  "17:24",
        "author":  "Mi juego del mes"
    },
    {
        "id":  "OIZ5edNh6Uo",
        "title":  "Skull Tales: Adventure Gameplay",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Gameplay (Aventura)",
        "year":  "2018",
        "lang":  "Inglés",
        "duration":  "51:42",
        "author":  "JueGorrinos"
    },
    {
        "id":  "9jZRZ-qc_fs",
        "title":  "Skull Tales: Full Sail! Episode 1 - Adventure Phase Rules and Playthrough",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Gameplay (Aventura)",
        "year":  "2019",
        "lang":  "Inglés",
        "duration":  "2:56:50",
        "author":  "HitPointsGaming"
    },
    {
        "id":  "smNTPq0dUs4",
        "title":  "Skull Tales: Full Sail! - Regel \u0026 Playthrough - Kampagne 1 Kapitel 1 - Port-Phase – deutsch",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Gameplay (Puerto)",
        "year":  "2019",
        "lang":  "Alemán",
        "duration":  "1:01:43",
        "author":  "Mr. Flexx"
    },
    {
        "id":  "fyBoqvqd7F0",
        "title":  "Skull Tales ¡A toda vela! Fase de Puerto",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Gameplay (Puerto)",
        "year":  "2018",
        "lang":  "Español",
        "duration":  "57:51",
        "author":  "Discípulos de Armitage"
    },
    {
        "id":  "O-gUCCE7AU0",
        "title":  "Skull Tales ¡A toda vela! Partida - Fase de Puerto",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Gameplay (Puerto)",
        "year":  "2019",
        "lang":  "Español",
        "duration":  "28:37",
        "author":  "Discípulos de Armitage"
    },
    {
        "id":  "K7VEl0APApw",
        "title":  "Lista de reproducción Skull Tales (Ejemplo Puerto)",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Gameplay (Puerto)",
        "year":  "2021",
        "lang":  "Español",
        "duration":  "7:22",
        "author":  "Mi juego del mes"
    },
    {
        "id":  "9bucF3nFjUg",
        "title":  "Skull Tales: Full Sail! - Playthrough - Kampagne 1 Kapitel 2 - Voyage-Phase – deutsch",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Gameplay (Travesía)",
        "year":  "2019",
        "lang":  "Alemán",
        "duration":  "1:40:53",
        "author":  "Mr. Flexx"
    },
    {
        "id":  "bHFnWxNOmfE",
        "title":  "Skull Tales ¡A toda vela! Fase de Travesía",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Gameplay (Travesía)",
        "year":  "2018",
        "lang":  "Español",
        "duration":  "1:05:13",
        "author":  "Discípulos de Armitage"
    },
    {
        "id":  "P3b-1dlyiWc",
        "title":  "Abordaje en Skull Tales ¡A toda vela!",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Gameplay (Travesía)",
        "year":  "2019",
        "lang":  "Español",
        "duration":  "15:02",
        "author":  "Discípulos de Armitage"
    },
    {
        "id":  "LAA-uikw-W4",
        "title":  "Skull Tales ¡A toda vela! Partida - Fase de Travesía",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Gameplay (Travesía)",
        "year":  "2019",
        "lang":  "Español",
        "duration":  "52:32",
        "author":  "Discípulos de Armitage"
    },
    {
        "id":  "YlqbKB47jls",
        "title":  "Lista de reproducción Skull Tales (Ejemplo Travesía)",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Gameplay (Travesía)",
        "year":  "2021",
        "lang":  "Español",
        "duration":  "16:03",
        "author":  "Mi juego del mes"
    },
    {
        "id":  "m34vQaUWET4",
        "title":  "Skull Tales: Full Sail! Custom Foam Core Insert / Organizer (Full Version of my Plan)",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Otros",
        "year":  "2019",
        "lang":  "Alemán",
        "duration":  "4:27",
        "author":  "Mr. Flexx"
    },
    {
        "id":  "5Wpq5PE7Y1g",
        "title":  "Skull Tales Full Sail! (Tuck Box and Plan / Caja plegable y plano) for Miniatures",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Otros",
        "year":  "2019",
        "lang":  "Alemán",
        "duration":  "11:13",
        "author":  "Mr. Flexx"
    },
    {
        "id":  "6o_jcsgcl9M",
        "title":  "Skull Tales: Full Sail! - 24 Hero Tuck Boxes / Cajas plegables Heroes",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Otros",
        "year":  "2019",
        "lang":  "Alemán",
        "duration":  "1:23",
        "author":  "Mr. Flexx"
    },
    {
        "id":  "Yd8H646E7oE",
        "title":  "Skull Tales: Full Sail!: 52 Tuck Boxes Core Game / Cajas plegables Juego Base",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Otros",
        "year":  "2019",
        "lang":  "Alemán",
        "duration":  "6:41",
        "author":  "Mr. Flexx"
    },
    {
        "id":  "Je2qgmZUF6s",
        "title":  "Skull Tales: Full Sail!: 42+7 Tuck Boxes Mega Expansion \u0026 Extras / Cajas plegables Mega Expansión",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Otros",
        "year":  "2019",
        "lang":  "Alemán",
        "duration":  "6:23",
        "author":  "Mr. Flexx"
    },
    {
        "id":  "_hvucsyadVY",
        "title":  "Inboxing: Skull Tales Full Sail! (Custom Foam Core Insert / Incrustación personalizada de foamcore)",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Otros",
        "year":  "2019",
        "lang":  "Alemán",
        "duration":  "13:48",
        "author":  "Mr. Flexx"
    },
    {
        "id":  "krF-DXw59Tw",
        "title":  "Unboxing: Skull Tales Full Sail! (Custom Foam Core Insert / Incrustación personalizada de foamcore)",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Otros",
        "year":  "2019",
        "lang":  "Alemán",
        "duration":  "15:52",
        "author":  "Mr. Flexx"
    },
    {
        "id":  "MfgXHO5SNcc",
        "title":  "Skull Tales: Full Sail! - Organizer Box Details",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Otros",
        "year":  "2019",
        "lang":  "No",
        "duration":  "9:15",
        "author":  "Mr. Flexx"
    },
    {
        "id":  "Wn2KDLQ9qho",
        "title":  "Skull Tales Full Sail Organizer in 50s!",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Otros",
        "year":  "2019",
        "lang":  "No",
        "duration":  "0:50",
        "author":  "Mr. Flexx"
    },
    {
        "id":  "VN8OdfBywgc",
        "title":  "Proyecto Kickstarter: Skull Tales ¡A toda vela!",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Presentaciones y entrevistas",
        "year":  "2017",
        "lang":  "Español",
        "duration":  "17:38",
        "author":  "Discípulos de Armitage"
    },
    {
        "id":  "3peZ8sX6654",
        "title":  "Skull Tales ¡A toda vela! - Presentación Kickstarter",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Presentaciones y entrevistas",
        "year":  "2018",
        "lang":  "Español",
        "duration":  "25:23",
        "author":  "Escapando del espacio reticulado"
    },
    {
        "id":  "-NaovIEWo4A",
        "title":  "Skull Tales: Full Sail! (A Toda Vela) – Presentación",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Presentaciones y entrevistas",
        "year":  "2018",
        "lang":  "Español",
        "duration":  "49:08",
        "author":  "Juegos de mesa 221B"
    },
    {
        "id":  "vPo8ETifKjU",
        "title":  "Skull Tales 2.0 (a toda vela): Nos lo presentan",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Presentaciones y entrevistas",
        "year":  "2018",
        "lang":  "Español",
        "duration":  "13:39",
        "author":  "La Mazmorra de Pacheco"
    },
    {
        "id":  "-SCKQFrgk6s",
        "title":  "Skull Tales 2.0: Presentación",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Presentaciones y entrevistas",
        "year":  "2018",
        "lang":  "Español",
        "duration":  "11:17",
        "author":  "La Mazmorra de Pacheco"
    },
    {
        "id":  "dZyV2E2QX8w",
        "title":  "¡Presentación de Skull Tales!",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Presentaciones y entrevistas",
        "year":  "2018",
        "lang":  "Español",
        "duration":  "1:10:57",
        "author":  "La Taberna de los Videojuegos"
    },
    {
        "id":  "EsimaTkPPS0",
        "title":  "Skull Tales 2.0 Nueva edición en español - Eclipse Editorial – Presentación",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Presentaciones y entrevistas",
        "year":  "2018",
        "lang":  "Español",
        "duration":  "9:23",
        "author":  "MiCabezaFriki"
    },
    {
        "id":  "4qcszKwQg5k",
        "title":  "Show me your Proto: Skull Tales ¡A Toda Vela! (con David Illescas)",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Presentaciones y entrevistas",
        "year":  "2018",
        "lang":  "Español",
        "duration":  "35:27",
        "author":  "MrPlayforlive"
    },
    {
        "id":  "Xrlp_w_29IE",
        "title":  "Skull Tales – Juego de mesa – Reseña/Aprende a jugar",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Presentaciones y entrevistas",
        "year":  "2018",
        "lang":  "Español",
        "duration":  "15:55",
        "author":  "Viciados mesa"
    },
    {
        "id":  "e8kNteMMG4I",
        "title":  "Cthuliño de autor: Skull Tales: ¡A toda vela!",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Presentaciones y entrevistas",
        "year":  "2018",
        "lang":  "Español",
        "duration":  "51:45",
        "author":  "Destroqueladores"
    },
    {
        "id":  "BtaAtPDp5d4",
        "title":  "Ampliando Skull Tales: Megaexpansión",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Presentaciones y entrevistas",
        "year":  "2019",
        "lang":  "Español",
        "duration":  "4:44",
        "author":  "Zacatrus"
    },
    {
        "id":  "ggXR2o17awo",
        "title":  "Skull Tales A Toda Vela – Entrevista: ¡Todas las novedades! Gamefound",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Presentaciones y entrevistas",
        "year":  "2021",
        "lang":  "Español",
        "duration":  "52:33",
        "author":  "Yo tenía un juego"
    },
    {
        "id":  "hP5U_Da9FQc",
        "title":  "Ampliando Skull Tales: Tortuga",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Presentaciones y entrevistas",
        "year":  "2021",
        "lang":  "Español",
        "duration":  "2:19",
        "author":  "Zacatrus"
    },
    {
        "id":  "mzpf_u5ZqNg",
        "title":  "Skull Tales Full Sails into Kickstarter",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Presentaciones y entrevistas",
        "year":  "2018",
        "lang":  "Inglés",
        "duration":  "5:55",
        "author":  "OnTableTop Clips"
    },
    {
        "id":  "Ny_F7VsrvQo",
        "title":  "Skull Tales ¡A toda vela!, primeras impresiones",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Reseñas y opiniones",
        "year":  "2017",
        "lang":  "Español",
        "duration":  "9:11",
        "author":  "Discípulos de Armitage"
    },
    {
        "id":  "70juqAq9PwM",
        "title":  "Skull Tales ¡A toda vela! Opinión",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Reseñas y opiniones",
        "year":  "2018",
        "lang":  "Español",
        "duration":  "27:42",
        "author":  "Discípulos de Armitage"
    },
    {
        "id":  "mqCMOqPCFfU",
        "title":  "Skull Tales ¡A toda vela! Reseña de juegos de mesa",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Reseñas y opiniones",
        "year":  "2019",
        "lang":  "Español",
        "duration":  "17:42",
        "author":  "Discípulos de Armitage"
    },
    {
        "id":  "O762W8HsnhY",
        "title":  "El Experto: Mage Knight VS Skull Tales",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Reseñas y opiniones",
        "year":  "2019",
        "lang":  "Español",
        "duration":  "11:11",
        "author":  "JueGorrinos"
    },
    {
        "id":  "o86CovNvxpY",
        "title":  "Lista de reproducción Skull Tales (Presentación y Conclusión)",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Reseñas y opiniones",
        "year":  "2021",
        "lang":  "Español",
        "duration":  "4:31",
        "author":  "Mi juego del mes"
    },
    {
        "id":  "pMbk4Lo_XZ4",
        "title":  "Skull Tales Full Sail Kickstarter Edition Board Game Review",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Reseñas y opiniones",
        "year":  "2019",
        "lang":  "Inglés",
        "duration":  "25:38",
        "author":  "Infinity Flux Comicx"
    },
    {
        "id":  "yF9W5KZ4lfs",
        "title":  "Skull Tales Full Sail - Take a look at the game, and the disaster of a rule book",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Reseñas y opiniones",
        "year":  "2019",
        "lang":  "Inglés",
        "duration":  "35:05",
        "author":  "The Dungeon Dive"
    },
    {
        "id":  "wXfBWLe636E",
        "title":  "Skull Tales: Full Sail! - Cosa ne penso?",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Reseñas y opiniones",
        "year":  "2020",
        "lang":  "Italiano",
        "duration":  "35:23",
        "author":  "Corydan"
    },
    {
        "id":  "CK3vlwaeEUQ",
        "title":  "Skull Tales minitutorial: Fase de Aventura",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Tutorial (Aventura)",
        "year":  "2018",
        "lang":  "Español",
        "duration":  "15:19",
        "author":  "Draco Ideas"
    },
    {
        "id":  "q5xn9JvvQ7k",
        "title":  "Skull Tales A Toda Vela - Tutorial - Fase de Aventuras",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Tutorial (Aventura)",
        "year":  "2019",
        "lang":  "Español",
        "duration":  "35:58",
        "author":  "Discípulos de Armitage"
    },
    {
        "id":  "kNgZeGijhOk",
        "title":  "Skull Tales – Fase de Aventuras - Combate (Tutorial 05)",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Tutorial (Aventura)",
        "year":  "2019",
        "lang":  "Español",
        "duration":  "18:27",
        "author":  "Yo tenía un juego"
    },
    {
        "id":  "SA9ZMp9ZMK4",
        "title":  "Aprende a jugar a Skull Tales: Fase de Aventura",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Tutorial (Aventura)",
        "year":  "2020",
        "lang":  "Español",
        "duration":  "19:10",
        "author":  "Walkyria Cómics"
    },
    {
        "id":  "5MTsmUZvt98",
        "title":  "Lista de reproducción Skull Tales (Acciones Aventura I, Acciones Aventura II, Turno Aventura)",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Tutorial (Aventura)",
        "year":  "2021",
        "lang":  "Español",
        "duration":  "14:45",
        "author":  "Mi juego del mes"
    },
    {
        "id":  "QwbCJk297DU",
        "title":  "Skull Tales minitutorial: Adventure Phase",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Tutorial (Aventura)",
        "year":  "2018",
        "lang":  "Inglés",
        "duration":  "12:31",
        "author":  "Draco Ideas"
    },
    {
        "id":  "rK_vo8EeRRg",
        "title":  "Skull Tales – Conceptos Generales (Tutorial 03)",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Tutorial",
        "year":  "2019",
        "lang":  "Español",
        "duration":  "13:13",
        "author":  "Yo tenía un juego"
    },
    {
        "id":  "HYIltFpUmiM",
        "title":  "Skull Tales – Introducción (Tutorial 01)",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Tutorial",
        "year":  "2019",
        "lang":  "Español",
        "duration":  "2:50",
        "author":  "Yo tenía un juego"
    },
    {
        "id":  "mbxfUdyJIBM",
        "title":  "Skull Tales – Modo PVP Pirata contra Pirata (Tutorial 02)",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Tutorial (PvP)",
        "year":  "2019",
        "lang":  "Español",
        "duration":  "10:05",
        "author":  "Yo tenía un juego"
    },
    {
        "id":  "JKoYy5ViKNM",
        "title":  "Skull Tales minitutorial: Fase de Puerto",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Tutorial (Puerto)",
        "year":  "2018",
        "lang":  "Español",
        "duration":  "8:52",
        "author":  "Draco Ideas"
    },
    {
        "id":  "EmLG1Q207FQ",
        "title":  "Skull Tales: A Toda Vela - Fase de Puerto - ¿Como se juega?",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Tutorial (Puerto)",
        "year":  "2018",
        "lang":  "Español",
        "duration":  "8:33",
        "author":  "Meepletopía"
    },
    {
        "id":  "ZkS2gL6cRro",
        "title":  "Aprende a jugar a Skull Tales: Fase de Puerto",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Tutorial (Puerto)",
        "year":  "2020",
        "lang":  "Español",
        "duration":  "7:43",
        "author":  "Walkyria Cómics"
    },
    {
        "id":  "h_VN1kSR3bA",
        "title":  "Lista de reproducción Skull Tales (Acciones Puerto, Turno Puerto)",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Tutorial (Puerto)",
        "year":  "2021",
        "lang":  "Español",
        "duration":  "13:46",
        "author":  "Mi juego del mes"
    },
    {
        "id":  "KbSEmv6Qc3E",
        "title":  "Skull Tales minitutorial: Port Phase",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Tutorial (Puerto)",
        "year":  "2018",
        "lang":  "Inglés",
        "duration":  "7:53",
        "author":  "Draco Ideas"
    },
    {
        "id":  "mO4PpHsQSa8",
        "title":  "Skull Tales: Full Sail! - Ablauf und Regeln - Voyage-Phase – deutsch",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Tutorial (Travesía)",
        "year":  "2019",
        "lang":  "Alemán",
        "duration":  "1:25:56",
        "author":  "Mr. Flexx"
    },
    {
        "id":  "2V6j_GNnFKk",
        "title":  "Skull Tales minitutorial: Fase de Travesía",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Tutorial (Travesía)",
        "year":  "2018",
        "lang":  "Español",
        "duration":  "11:11",
        "author":  "Draco Ideas"
    },
    {
        "id":  "OXgGOMoeqPY",
        "title":  "Skull Tales: A Toda Vela - Fase de Travesía - ¿Como se juega?",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Tutorial (Travesía)",
        "year":  "2018",
        "lang":  "Español",
        "duration":  "11:00",
        "author":  "Meepletopía"
    },
    {
        "id":  "8Z84EDMiqy8",
        "title":  "Skull Tales A Toda Vela - Tutorial - Fase de Travesía",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Tutorial (Travesía)",
        "year":  "2019",
        "lang":  "Español",
        "duration":  "54:01",
        "author":  "Discípulos de Armitage"
    },
    {
        "id":  "ei3WwvcOtUo",
        "title":  "Aprende a jugar a Skull Tales: Fase de Travesía",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Tutorial (Travesía)",
        "year":  "2020",
        "lang":  "Español",
        "duration":  "25:30",
        "author":  "Walkyria Cómics"
    },
    {
        "id":  "0x_Sy6cnc3k",
        "title":  "Lista de reproducción Skull Tales (Acciones Travesía I, Acciones Travesía II, Turno Travesía)",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Tutorial (Travesía)",
        "year":  "2021",
        "lang":  "Español",
        "duration":  "13:50",
        "author":  "Mi juego del mes"
    },
    {
        "id":  "QaRllccYIqU",
        "title":  "Skull Tales minitutorial: Voyage Phase",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Tutorial (Travesía)",
        "year":  "2018",
        "lang":  "Inglés",
        "duration":  "9:58",
        "author":  "Draco Ideas"
    },
    {
        "id":  "AKg85xI4qO8",
        "title":  "Unboxing: Skull Tales: Full Sail! Karten-Erweiterung Tortuga (deutsch / german)",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Componentes y Unboxing",
        "year":  "2021",
        "lang":  "Alemán",
        "duration":  "6:05",
        "author":  "Mr. Flexx"
    },
    {
        "id":  "BBqMAWymJwE",
        "title":  "Skull Tales #2 Expansión Tortuga",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Componentes y Unboxing",
        "year":  "2021",
        "lang":  "Español",
        "duration":  "10:18",
        "author":  "La zona lúdica de WulfricOMG"
    },
    {
        "id":  "PVotfbVsu2c",
        "title":  "Skull Tales – Contenido",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Componentes y Unboxing",
        "year":  "2021",
        "lang":  "Español",
        "duration":  "27:22",
        "author":  "La partida de los sábados"
    },
    {
        "id":  "0GULqMUKQYE",
        "title":  "Unboxing Skull Tales edición de 2022",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Componentes y Unboxing",
        "year":  "2022",
        "lang":  "Español",
        "duration":  "19:41",
        "author":  "Discípulos de Armitage"
    },
    {
        "id":  "Gd5qxmMnfg8",
        "title":  "Hoy presentamos… Skul Tales – Héroes – Imperial Struggle",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Componentes y Unboxing",
        "year":  "2022",
        "lang":  "Español",
        "duration":  "3:06:16",
        "author":  "Escapando del espacio reticulado"
    },
    {
        "id":  "o1Zqh-dQUu0",
        "title":  "Skull Tales: Abriendo el cajote",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Componentes y Unboxing",
        "year":  "2022",
        "lang":  "Español",
        "duration":  "30:02",
        "author":  "Escapando del espacio reticulado"
    },
    {
        "id":  "Ax83lmPurEM",
        "title":  "Abriendo Skull Tales ¡A Toda Vela!",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Componentes y Unboxing",
        "year":  "2022",
        "lang":  "Español",
        "duration":  "12:30",
        "author":  "Jugones Deluxe"
    },
    {
        "id":  "1a7iLpyFexY",
        "title":  "Skull Tales – Unboxing 2022",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Componentes y Unboxing",
        "year":  "2022",
        "lang":  "Español",
        "duration":  "1:07:34",
        "author":  "Rapsoda Lúdico"
    },
    {
        "id":  "22lkgllEpzQ",
        "title":  "Skull Tales: A Toda Vela – Unboxing",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Componentes y Unboxing",
        "year":  "2022",
        "lang":  "Español",
        "duration":  "30:48",
        "author":  "Rescue Gamer"
    },
    {
        "id":  "Vnfh0tp2E44",
        "title":  "Skull Tales A toda vela – Dentro de la caja – Unboxing juego de mesa",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Componentes y Unboxing",
        "year":  "2022",
        "lang":  "Español",
        "duration":  "18:54",
        "author":  "Unna"
    },
    {
        "id":  "u1o6x5mrFNI",
        "title":  "Unboxing de Actualización de Skull Tales",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Componentes y Unboxing",
        "year":  "2023",
        "lang":  "Español",
        "duration":  "20:12",
        "author":  "Alternativa Juegos de Mesa"
    },
    {
        "id":  "eHzUKboEGYs",
        "title":  "Unboxin de Skull Tales!!! Y un paquete de salchichas",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Componentes y Unboxing",
        "year":  "2023",
        "lang":  "Español",
        "duration":  "15:36",
        "author":  "El agujero Hobbit"
    },
    {
        "id":  "hPPMAhZHX8E",
        "title":  "Skull Tales. A Toda Vela (segunda edición) – Dentro de la caja – Unboxing",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Componentes y Unboxing",
        "year":  "2023",
        "lang":  "Español",
        "duration":  "15:12",
        "author":  "Ines Juegos y más"
    },
    {
        "id":  "vBQ_FySpbis",
        "title":  "Unboxing 04 X 27 Skull Tales ¡A Toda Vela! (Eclipse Editorial)",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Componentes y Unboxing",
        "year":  "2023",
        "lang":  "Español",
        "duration":  "24:51",
        "author":  "Territorio Oca"
    },
    {
        "id":  "n3tyX-hN_UU",
        "title":  "Skull Tales: ¡A Toda Vela! –  Unboxing de la caja base",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Componentes y Unboxing",
        "year":  "2024",
        "lang":  "Español",
        "duration":  "27:41",
        "author":  "A solas con Lumerien"
    },
    {
        "id":  "dc7jLRwh2TU",
        "title":  "Skull Tales Unboxing y campaña de Gameofound explicada",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Componentes y Unboxing",
        "year":  "2025",
        "lang":  "Español",
        "duration":  "24:20",
        "author":  "Aventureros al juego"
    },
    {
        "id":  "4kJ1G7vQP1I",
        "title":  "Ron por aquí, motín por allá. ¿Cómo se llama este programa?",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Componentes y Unboxing",
        "year":  "2025",
        "lang":  "Español",
        "duration":  "1:09:54",
        "author":  "Dámaso de Damasco y sus distracciones"
    },
    {
        "id":  "uw1QzU2JNnA",
        "title":  "Skull Tales: Full Sail! From Eclipse Editorial unboxing",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Componentes y Unboxing",
        "year":  "2023",
        "lang":  "Ingles",
        "duration":  "17:16",
        "author":  "So Play We All"
    },
    {
        "id":  "ATFpex9cMpE",
        "title":  "Unboxing Skull Tales: Full Sail, 2nd Edition!",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Componentes y Unboxing",
        "year":  "2024",
        "lang":  "Inglés",
        "duration":  "56:08",
        "author":  "Talking Cardboard"
    },
    {
        "id":  "4kkoy2CMn9M",
        "title":  "Miniaturas de Skull Tales: ¡A toda Vela! 2ª Edición",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Componentes y Unboxing",
        "year":  "2022",
        "lang":  "No",
        "duration":  "0:42",
        "author":  "Draco Ideas"
    },
    {
        "id":  "q2r3o8gpLEk",
        "title":  "Unboxing dados Skull Tales: ¡A toda Vela!",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Componentes y Unboxing",
        "year":  "2022",
        "lang":  "No",
        "duration":  "0:44",
        "author":  "Draco Ideas"
    },
    {
        "id":  "8zTliQm3QPU",
        "title":  "Unboxing Preproducción Skull Tales 2ª edición",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Componentes y Unboxing",
        "year":  "2022",
        "lang":  "No",
        "duration":  "4:38",
        "author":  "Draco Ideas"
    },
    {
        "id":  "1q373yOD7KE",
        "title":  "Big Pirate Chest (Prototipo)",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Componentes y Unboxing",
        "year":  "2025",
        "lang":  "No",
        "duration":  "1:08",
        "author":  "Draco Ideas"
    },
    {
        "id":  "FcIzH7A6JGM",
        "title":  "Tráiler “Skull Tales ¡A toda vela!” en Gamefound",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Crowdfunding, Trailers y Campañas",
        "year":  "2025",
        "lang":  "Español",
        "duration":  "2:01",
        "author":  "Draco Ideas"
    },
    {
        "id":  "5dLRX71XNXc",
        "title":  "Tráiler “Skull Tales ¡A toda vela!” en Gamefound",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Crowdfunding, Trailers y Campañas",
        "year":  "2025",
        "lang":  "Inglés",
        "duration":  "2:01",
        "author":  "Draco Ideas"
    },
    {
        "id":  "41lVLC06D7E",
        "title":  "Lets Play Solo: Skull Tales: Full Sail! (Adventure Phase #1/7 – remastered)",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Aventura)",
        "year":  "2024",
        "lang":  "Alemán",
        "duration":  "30:30",
        "author":  "Mr. Flexx"
    },
    {
        "id":  "5FtIt5-JBEc",
        "title":  "Lets Play Solo: Skull Tales: Full Sail! (Adventure Phase #2/7 – remastered)",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Aventura)",
        "year":  "2024",
        "lang":  "Alemán",
        "duration":  "28:15",
        "author":  "Mr. Flexx"
    },
    {
        "id":  "M1_SpqWminU",
        "title":  "Lets Play Solo: Skull Tales: Full Sail! (Adventure Phase #3/7 – remastered)",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Aventura)",
        "year":  "2024",
        "lang":  "Alemán",
        "duration":  "29:45",
        "author":  "Mr. Flexx"
    },
    {
        "id":  "j0jGDC5oxCM",
        "title":  "Lets Play Solo: Skull Tales: Full Sail! (Adventure Phase #4/7 – remastered)",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Aventura)",
        "year":  "2024",
        "lang":  "Alemán",
        "duration":  "20:40",
        "author":  "Mr. Flexx"
    },
    {
        "id":  "OXkyrIq1izE",
        "title":  "Lets Play Solo: Skull Tales: Full Sail! (Adventure Phase #5/7 - remastered / director\u0027s cut)",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Aventura)",
        "year":  "2024",
        "lang":  "Alemán",
        "duration":  "25:45",
        "author":  "Mr. Flexx"
    },
    {
        "id":  "-zzTlVKaz2E",
        "title":  "Lets Play Solo: Skull Tales: Full Sail! (Adventure Phase #6/7 - remastered / director\u0027s cut)",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Aventura)",
        "year":  "2024",
        "lang":  "Alemán",
        "duration":  "17:11",
        "author":  "Mr. Flexx"
    },
    {
        "id":  "sY40VblKhLA",
        "title":  "Lets Play Solo: Skull Tales: Full Sail! (Adventure Phase #7/7 - remastered / director\u0027s cut)",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Aventura)",
        "year":  "2024",
        "lang":  "Alemán",
        "duration":  "19:20",
        "author":  "Mr. Flexx"
    },
    {
        "id":  "yiSA2Y14psc",
        "title":  "Skull Tales #1 Fase de Aventuras - Sombras del Caribe - Capítulo I – Directo",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Aventura)",
        "year":  "2021",
        "lang":  "Español",
        "duration":  "1:31:22",
        "author":  "La zona lúdica de WulfricOMG"
    },
    {
        "id":  "Fx5fkETosJY",
        "title":  "Skull Tales: A Toda Vela 2ª Edición – 1. Fase de Aventura Tutorial + Partida",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Aventura)",
        "year":  "2022",
        "lang":  "Español",
        "duration":  "2:33:27",
        "author":  "Rescue Gamer"
    },
    {
        "id":  "6iWHaC5Dx78",
        "title":  "Cómo se juega 06x04 Skull Tales, parte 1 (Eclipse Editorial)",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Aventura)",
        "year":  "2023",
        "lang":  "Español",
        "duration":  "40:13",
        "author":  "Territorio Oca"
    },
    {
        "id":  "3x6bHOwaA-k",
        "title":  "Partidoca 06x02 Skull Tales (Eclipse Editorial) Parte 1",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Aventura)",
        "year":  "2023",
        "lang":  "Español",
        "duration":  "2:13:27",
        "author":  "Territorio Oca"
    },
    {
        "id":  "O8fHr5rJoVU",
        "title":  "Partidoca 05x24 Skull Tales (Eclipse Editorial)",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Aventura)",
        "year":  "2023",
        "lang":  "Español",
        "duration":  "2:47:55",
        "author":  "Territorio Oca"
    },
    {
        "id":  "a13rQzX2EwM",
        "title":  "¡Jugando con Skull Tales! Con La Mazmorra de Pacheco y Dracoideas",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Aventura)",
        "year":  "2024",
        "lang":  "Español",
        "duration":  "1:03:26",
        "author":  "Loot \u0026 Fire"
    },
    {
        "id":  "1H--LBAMVbk",
        "title":  "Partida Skull Tales – Capítulo 1: El secreto del Capitán Jones",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Aventura)",
        "year":  "2025",
        "lang":  "Español",
        "duration":  "3:52:19",
        "author":  "Dámaso de Damasco y sus distracciones"
    },
    {
        "id":  "W1copaGeNec",
        "title":  "Partida Skull Tales – Capítulo 2: Despertad de la Oscuridad",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Aventura)",
        "year":  "2025",
        "lang":  "Español",
        "duration":  "5:38:48",
        "author":  "Dámaso de Damasco y sus distracciones"
    },

    {
        "id":  "1hivFPGDScg",
        "title":  "¡Jugamos a ser Piratas! Skull Tales – El diario de Lobo Jones",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Aventura)",
        "year":  "2025",
        "lang":  "Español",
        "duration":  "1:44:04",
        "author":  "La Mazmorra de Pacheco"
    },
    {
        "id":  "4YnlUvr1eug",
        "title":  "Jugamos a Skull Tales",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Aventura)",
        "year":  "2025",
        "lang":  "Español",
        "duration":  "1:23:53",
        "author":  "Meepletopía"
    },
    {
        "id":  "-KIL-f01M8E",
        "title":  "Skull Tales: chapitre 1 le secret du Capitaine jones",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Aventura)",
        "year":  "2024",
        "lang":  "Francés",
        "duration":  "3:13:22",
        "author":  "Maximus-society"
    },
    {
        "id":  "Ic94jZ_CTt8",
        "title":  "Skull Tales: Full Sail playthrough",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Aventura)",
        "year":  "2025",
        "lang":  "Ingles",
        "duration":  "1:24:54",
        "author":  "So Play We All"
    },
    {
        "id":  "v-BZVcjyFxg",
        "title":  "Skull Tales: The Secret of Captain Jones Part ½",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Aventura)",
        "year":  "2022",
        "lang":  "Inglés",
        "duration":  "48:21",
        "author":  "Die Rollin´"
    },
    {
        "id":  "J7paSzQ_Yaw",
        "title":  "Skull Tales: The Secret of Captain Jones Part 2/2",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Aventura)",
        "year":  "2022",
        "lang":  "Inglés",
        "duration":  "49:43",
        "author":  "Die Rollin´"
    },
    {
        "id":  "6InhilOmQd0",
        "title":  "Skull Tales: Full Sail (2nd Edition) Live Playthrough! (Part 1)",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Aventura)",
        "year":  "2024",
        "lang":  "Inglés",
        "duration":  "1:32:12",
        "author":  "Talking Cardboard"
    },
    {
        "id":  "IIxt0VKdvhM",
        "title":  "Skull Tales: Full Sail (2nd Edition) Live Playthrough! (Part 2)",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Aventura)",
        "year":  "2024",
        "lang":  "Inglés",
        "duration":  "1:08:35",
        "author":  "Talking Cardboard"
    },
    {
        "id":  "6sexwlQ1RQs",
        "title":  "Skull Tales: Full Sail (2nd Edition) Live Playthrough! (Part 3)",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Aventura)",
        "year":  "2024",
        "lang":  "Inglés",
        "duration":  "1:09:46",
        "author":  "Talking Cardboard"
    },
    {
        "id":  "RSbyOlJnCMQ",
        "title":  "Skull Tales: Full Sail (2nd Edition) Live Playthrough! (Part 4)",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Aventura)",
        "year":  "2024",
        "lang":  "Inglés",
        "duration":  "1:17:48",
        "author":  "Talking Cardboard"
    },
    {
        "id":  "w9LacTlCiuE",
        "title":  "Skull Tales: Full Sail! (2nd Edition) | Game Overview \u0026 Gameplay",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Aventura)",
        "year":  "2025",
        "lang":  "Inglés",
        "duration":  "57:11",
        "author":  "Rolling Solo"
    },
    {
        "id":  "k-0YkeMuNzY",
        "title":  "Skull Tales 2nd Edition Playthrough! (Part 1)",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Aventura)",
        "year":  "2025",
        "lang":  "Inglés",
        "duration":  "1:36:34",
        "author":  "Talking Cardboard"
    },
    {
        "id":  "asgtczO5yy0",
        "title":  "Skull Tales 2nd Edition Playthrough! (Part 2)",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Aventura)",
        "year":  "2025",
        "lang":  "Inglés",
        "duration":  "1:14:35",
        "author":  "Talking Cardboard"
    },

    {
        "id":  "k-g-02lQqu8",
        "title":  "Skull Tales #2 Fase de Puerto - Sombras del Caribe - Capítulo II",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Puerto)",
        "year":  "2021",
        "lang":  "Español",
        "duration":  "31:08",
        "author":  "La zona lúdica de WulfricOMG"
    },
    {
        "id":  "dpNPe0Mzavo",
        "title":  "Skull Tales: A Toda Vela 2ª Edición – 2. Fase de Puerto Tutorial + Partida",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Puerto)",
        "year":  "2023",
        "lang":  "Español",
        "duration":  "48:12",
        "author":  "Rescue Gamer"
    },
    {
        "id":  "jspHr0ld6P4",
        "title":  "Cómo se juega 06x05 Skull Tales, parte 2 (Eclipse Editorial)",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Puerto)",
        "year":  "2023",
        "lang":  "Español",
        "duration":  "31:15",
        "author":  "Territorio Oca"
    },
    {
        "id":  "r19JdUML69M",
        "title":  "Skull Tales ¡A toda vela! Fase de Puerto",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Puerto)",
        "year":  "2025",
        "lang":  "Español",
        "duration":  "47:58",
        "author":  "La Mazmorra de Pacheco"
    },
    {
        "id":  "2weD_Hq91Y8",
        "title":  "Skull Tales Episode 3 Port Phase",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Puerto)",
        "year":  "2023",
        "lang":  "Inglés",
        "duration":  "32:16",
        "author":  "Die Rollin´"
    },
    {
        "id":  "3wBTTFw_dEo",
        "title":  "Skull Tales: Full Sail! 2nd Ed. Playthrough-Port Phase",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Puerto)",
        "year":  "2025",
        "lang":  "Inglés",
        "duration":  "1:07:34",
        "author":  "Talking Cardboard"
    },
    {
        "id":  "YNUVfxgVrbw",
        "title":  "Skull Tales: A Toda Vela 2ª Edición – 3. Fase de Travesía Tutorial + Partida",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Travesía)",
        "year":  "2023",
        "lang":  "Español",
        "duration":  "1:45:05",
        "author":  "Rescue Gamer"
    },
    {
        "id":  "_9F_NW7gsqM",
        "title":  "Cómo se juega 06x06 Skull Tales, parte 3 (Eclipse Editorial)",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Travesía)",
        "year":  "2023",
        "lang":  "Español",
        "duration":  "37:39",
        "author":  "Territorio Oca"
    },
    {
        "id":  "E2M79wLZiKI",
        "title":  "Partida Skull Tales – Capítulo 3: Exilio",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Travesía)",
        "year":  "2025",
        "lang":  "Español",
        "duration":  "2:19:50",
        "author":  "Dámaso de Damasco y sus distracciones"
    },
    {
        "id":  "EOA2QZIfwa0",
        "title":  "Partida Skull Tales – Capítulo 3: Exilio",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Aventura)",
        "year":  "2025",
        "lang":  "Español",
        "duration":  "2:42:07",
        "author":  "Dámaso de Damasco y sus distracciones"
    },	
    {
        "id":  "E2M79wLZiKI",
        "title":  "Partida Skull Tales – Capítulo 3: Exilio",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Puerto)",
        "year":  "2025",
        "lang":  "Español",
        "duration":  "2:19:50",
        "author":  "Dámaso de Damasco y sus distracciones"
    },
    {
        "id":  "EEHKrsXa1dU",
        "title":  "Partida Skull Tales – Capítulo 4: El cristal alquímico",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Capítulo)",
        "year":  "2025",
        "lang":  "Español",
        "duration":  "45:30",
        "author":  "Dámaso de Damasco y sus distracciones"
    },
    {
        "id":  "zcGg_9H8Tio",
        "title":  "Partida Skull Tales Capítulo 5 La isla maldita",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Puerto)",
        "year":  "2025",
        "lang":  "Español",
        "duration":  "1:22:09",
        "author":  "Dámaso de Damasco y sus distracciones"
    },
    {
        "id":  "gqHOLU6WieY",
        "title":  "Skull Tales Voyage Phase",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Travesía)",
        "year":  "2023",
        "lang":  "Inglés",
        "duration":  "1:10:07",
        "author":  "Die Rollin´"
    },
    {
        "id":  "qEIfMkMZFo0",
        "title":  "Skull Tales: Full Sail! 2nd Ed. Playthrough-Voyage Phase",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Gameplay (Travesía)",
        "year":  "2025",
        "lang":  "Inglés",
        "duration":  "1:11:56",
        "author":  "Talking Cardboard"
    },
    {
        "id":  "7TkmVRHvZsg",
        "title":  "Skull Tales – Cómo usar el mod de TTS",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Otros",
        "year":  "2020",
        "lang":  "Español",
        "duration":  "18:40",
        "author":  "Gilberto Guillén"
    },
    {
        "id":  "uiIDP7TJSic",
        "title":  "Reeditando Skull Tales",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Presentaciones y entrevistas",
        "year":  "2019",
        "lang":  "Español",
        "duration":  "12:06",
        "author":  "Zacatrus"
    },
    {
        "id":  "ucanQHUanHg",
        "title":  "¡Nuevo Skull Tales! Y más novedades de Eclipse \u0026 Dracoideas",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Presentaciones y entrevistas",
        "year":  "2022",
        "lang":  "Español",
        "duration":  "21:45",
        "author":  "La Mazmorra de Pacheco"
    },
    {
        "id":  "8NDB7aL0TDE",
        "title":  "Conociendo Skull Tales ¡A Toda Vela! (2ª Edición)",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Presentaciones y entrevistas",
        "year":  "2022",
        "lang":  "Español",
        "duration":  "10:23",
        "author":  "Zacatrus"
    },
    {
        "id":  "-UkxH6cgSNA",
        "title":  "¡Hablamos con el creador de Skull Tales!",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Presentaciones y entrevistas",
        "year":  "2025",
        "lang":  "Español",
        "duration":  "1:01:17",
        "author":  "Discípulos de Armitage"
    },
    {
        "id":  "y9Oua-O2FWI",
        "title":  "Skull Tales el Regreso. Novedades de juegos de mesa 2025",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Presentaciones y entrevistas",
        "year":  "2025",
        "lang":  "Español",
        "duration":  "49:58",
        "author":  "Discípulos de Armitage"
    },
    {
        "id":  "GtMIejdmGsk",
        "title":  "Presentación Gamefound Skull Tales",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Presentaciones y entrevistas",
        "year":  "2025",
        "lang":  "Español",
        "duration":  "44:44",
        "author":  "Gostilian"
    },
    {
        "id":  "_U4vnK8P_pY",
        "title":  "Últimas horas de Skull Tales V2 en Gamefound – Con Piru de Eclipse Editorial",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Presentaciones y entrevistas",
        "year":  "2025",
        "lang":  "Español",
        "duration":  "45:42",
        "author":  "Juegos de mesa 221B"
    },
    {
        "id":  "eNHz483nGS8",
        "title":  "Skull Tales 2ª Edición – Crawler de Piratas – Entrevista y nueva campaña",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Presentaciones y entrevistas",
        "year":  "2025",
        "lang":  "Español",
        "duration":  "34:41",
        "author":  "Los juegos de Ávatar"
    },
    {
        "id":  "kje749oVbek",
        "title":  "¡Prepárate para una épica aventura de piratas con Skull Tales!",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Presentaciones y entrevistas",
        "year":  "2025",
        "lang":  "Español",
        "duration":  "53:17",
        "author":  "Rapsoda Lúdico"
    },
    {
        "id":  "6TjMHF5Oh_4",
        "title":  "Skull Tales – ¡Pregunta al autor en directo!",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Presentaciones y entrevistas",
        "year":  "2025",
        "lang":  "Español",
        "duration":  "1:28:05",
        "author":  "Yo tenía un juego"
    },
    {
        "id":  "1ceb9pmFOII",
        "title":  "Skull Tales vuelve al abordaje! nueva campaña y expansiones",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Presentaciones y entrevistas",
        "year":  "2025",
        "lang":  "Español",
        "duration":  "29:48",
        "author":  "Nachere video \u0026 board gamer"
    },
    {
        "id":  "91ScRjRWMsU",
        "title":  "Skull Tales Paquisto CustomBox",
        "version":  "Skull Tales",
        "type":  "Otros",
        "year":  "2016",
        "lang":  "Español",
        "duration":  "8:25",
        "author":  "Paquisto CustomBox"
    },	
    {
        "id":  "znuLN703M9E",
        "title":  "Abriendo Skull Tales",
        "version":  "Skull Tales",
        "type":  "Componentes y Unboxing",
        "year":  "2016",
        "lang":  "Español",
        "duration":  "8:19",
        "author":  "Zacatrus"
    },
    {
        "id":  "z_F2CDxy0Bg",
        "title":  "Jugamos A Skull Tales",
        "version":  "Skull Tales",
        "type":  "Gameplay (Capítulo)",
        "year":  "2017",
        "lang":  "Español",
        "duration":  "1:26:40",
        "author":  "Zacatrus"
    },
    {
        "id":  "GoH_Bf2ZixM",
        "title":  "SKULL TALES ¡A TODA VELA!, ORGANIZANDO",
        "version":  "Skull Tales: A Toda Vela",
        "type":  "Otros",
        "year":  "2019",
        "lang":  "Español",
        "duration":  "5:43",
        "author":  "Cool Games"
    },
    {
        "id":  "LY-HS3Hh3Vg",
        "title":  "Skull Tales - Seconda Edizione",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Reseñas y opiniones",
        "year":  "2024",
        "lang":  "Italiano",
        "duration":  "12:24",
        "author":  "Corydan"
    },
    {
        "id":  "jUylKUaKMqg",
        "title":  "Skull Tales el Mejor juego de piratas",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Reseñas y opiniones",
        "year":  "2022",
        "lang":  "Español",
        "duration":  "4:46",
        "author":  "Discípulos de Armitage"
    },
    {
        "id":  "TGDn1zSOxWs",
        "title":  "Skull Tales: La reseña",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Reseñas y opiniones",
        "year":  "2023",
        "lang":  "Español",
        "duration":  "31:36",
        "author":  "Escapando del espacio reticulado"
    },
    {
        "id":  "23Arbau8WPg",
        "title":  "Skull Tales Primeras impresiones después de probarlo en Interocio",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Reseñas y opiniones",
        "year":  "2025",
        "lang":  "Español",
        "duration":  "12:12",
        "author":  "Aventureros al juego"
    },
    {
        "id":  "yJgISVjNv6k",
        "title":  "Skull Tales: ¡Análisis a fondo tras la campaña! ¿Merece la pena? Comentado por fases",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Reseñas y opiniones",
        "year":  "2025",
        "lang":  "Español",
        "duration":  "1:35:41",
        "author":  "Juegos de mesa en solitario"
    },
    {
        "id":  "7-w867o8EO8",
        "title":  "Lo mejor y lo peor de Skull Tales A toda Vela",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Reseñas y opiniones",
        "year":  "2025",
        "lang":  "Español",
        "duration":  "11:27",
        "author":  "Jugamos en Mesa"
    },
    {
        "id":  "rfCAjJ-Bdqg",
        "title":  "Skull Tales: ¡A Toda Vela! - 2ª Edición – Simulador de Pirata épico",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Reseñas y opiniones",
        "year":  "2025",
        "lang":  "Español",
        "duration":  "5:52",
        "author":  "Painting Fanatic"
    },
    {
        "id":  "GV_CFB0enrg",
        "title":  "Skull Tales - La piraterie dans tous ses aspects",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Reseñas y opiniones",
        "year":  "2024",
        "lang":  "Francés",
        "duration":  "2:53:31",
        "author":  "Etrigane"
    },
    {
        "id":  "N2w0_c0ibmY",
        "title":  "Skull Tales: Full Sail! with Ray",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Reseñas y opiniones",
        "year":  "2024",
        "lang":  "Ingles",
        "duration":  "42:12",
        "author":  "The Discriminating Gamer"
    },
    {
        "id":  "caWJLvsM6UY",
        "title":  "Skull Tales Full Sail! Second Edition) \u0026 Expansions - A Preview Video",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Reseñas y opiniones",
        "year":  "2025",
        "lang":  "Ingles",
        "duration":  "17:58",
        "author":  "Epitrapaizoume"
    },
    {
        "id":  "NA_77KxkCyI",
        "title":  "The Hungry Gamer Reviews Skull Tales Full Sail 2nd Edition",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Reseñas y opiniones",
        "year":  "2024",
        "lang":  "Inglés",
        "duration":  "53:16",
        "author":  "Hungry Gamer"
    },
    {
        "id":  "wPPzzooeJmA",
        "title":  "Skull Tales: Full Sail! 2nd Edition - Board Game Review",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Reseñas y opiniones",
        "year":  "2025",
        "lang":  "Inglés",
        "duration":  "21:19",
        "author":  "Talking Cardboard"
    },
    {
        "id":  "OgFnbLaxkrk",
        "title":  "Lets Play Solo: Skull Tales: Full Sail! (Adventure Phase #0/7 – remastered)",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Tutorial (Aventura)",
        "year":  "2024",
        "lang":  "Alemán",
        "duration":  "27:25",
        "author":  "Mr. Flexx"
    },
    {
        "id":  "7UC9lUQ4nHk",
        "title":  "Skull Tales A Toda Vela Fase de Aventuras (⅓) Cómo se juega – Tutorial",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Tutorial (Aventura)",
        "year":  "2022",
        "lang":  "Español",
        "duration":  "50:40",
        "author":  "Unna"
    },
    {
        "id":  "XhyHoKXj4fo",
        "title":  "Skull Tales: ¡A Toda Vela! Fase de Aventura",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Tutorial (Aventura)",
        "year":  "2025",
        "lang":  "Español",
        "duration":  "11:45",
        "author":  "Altru no existe"
    },
    {
        "id":  "CFxY4IKmddc",
        "title":  "Skull Tales. Tutorial. Introducción y conceptos generales",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Tutorial",
        "year":  "2025",
        "lang":  "Español",
        "duration":  "20:19",
        "author":  "Gostilian"
    },
    {
        "id":  "LyVf7bzMc-4",
        "title":  "Skull Tales A Toda Vela Fase de Puerto (3/3) Cómo se juega – Tutorial",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Tutorial (Puerto)",
        "year":  "2022",
        "lang":  "Español",
        "duration":  "25:47",
        "author":  "Unna"
    },
    {
        "id":  "B8ozqR-rgXI",
        "title":  "Skull Tales: ¡A Toda Vela! Fase de Puerto",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Tutorial (Puerto)",
        "year":  "2025",
        "lang":  "Español",
        "duration":  "9:52",
        "author":  "Altru no existe"
    },
    {
        "id":  "_1gjn97skBA",
        "title":  "Skull Tales A Toda Vela Fase de Travesía (⅔) Cómo se juega – Tutorial",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Tutorial (Travesía)",
        "year":  "2022",
        "lang":  "Español",
        "duration":  "52:32",
        "author":  "Unna"
    },
    {
        "id":  "chUzukkXND4",
        "title":  "Skull Tales: ¡A Toda Vela! Fase de Travesía",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Tutorial (Travesía)",
        "year":  "2025",
        "lang":  "Español",
        "duration":  "10:14",
        "author":  "Altru no existe"
    },
    {
        "id":  "U8BnoPdlm5E",
        "title":  "Skull Tales – Tutorial Abordajes – Ejemplo 1",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Tutorial (Travesía)",
        "year":  "2025",
        "lang":  "Español",
        "duration":  "37:08",
        "author":  "Cristian TG"
    },
    {
        "id":  "ikLzymugfwo",
        "title":  "Skull Tales – Tutorial Abordajes – Ejemplo 2",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Tutorial (Travesía)",
        "year":  "2025",
        "lang":  "Español",
        "duration":  "19:53",
        "author":  "Cristian TG"
    },
    {
        "id":  "LkXeE1K-Kj0",
        "title":  "Skull Tales – Tutorial Abordajes – Ejemplo 3",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Tutorial (Travesía)",
        "year":  "2025",
        "lang":  "Español",
        "duration":  "25:23",
        "author":  "Cristian TG"
    },
    {
        "id":  "Vb3uhf2dhYw",
        "title":  "Skull Tales – Tutorial Abordajes – Vídeo Introductorio",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Tutorial (Travesía)",
        "year":  "2025",
        "lang":  "Español",
        "duration":  "4:17",
        "author":  "Cristian TG"
    },
    {
        "id":  "1gOoJL5Q89o",
        "title":  "Skull Tales. Tutorial. Fase de Travesía",
        "version":  "Skull Tales: A Toda Vela (segunda edición)",
        "type":  "Tutorial (Travesía)",
        "year":  "2025",
        "lang":  "Español",
        "duration":  "59:38",
        "author":  "Gostilian"
    }
];

const videoOptions = {
    "types":  [
                  "Todos",
                  "Componentes y Unboxing",
                  "Crowdfunding, Trailers y Campañas",
                  "Gameplay (Aventura)",
                  "Gameplay (Capítulo)",
                  "Gameplay (Puerto)",
                  "Gameplay (Travesía)",
                  "Otros",
                  "Presentaciones y entrevistas",
                  "Reseñas y opiniones",
                  "Tutorial",
                  "Tutorial (Aventura)",
                  "Tutorial (Puerto)",
                  "Tutorial (PvP)",
                  "Tutorial (Travesía)"
              ],
    "authors":  [
                    "Todos",
                    "¡Jugad, insensatos!",
                    "5 Minutos por juego",
                    "A solas con Lumerien",
                    "Alternativa Juegos de Mesa",
                    "Altru no existe",
                    "Análisis Parálisis",
                    "Aventureros al juego",
                    "Cool Games",
                    "Corydan",
                    "Cristian TG",
                    "Dámaso de Damasco y sus distracciones",
                    "Destroqueladores",
                    "Die Rollin´",
                    "Discípulos de Armitage",
                    "Draco Ideas",
                    "El agujero Hobbit",
                    "El Rincón del Meeple",
                    "Epitrapaizoume",
                    "Escapando del espacio reticulado",
                    "Etrigane",
                    "Funattic Channel",
                    "Gilberto Guillén",
                    "Gostilian",
                    "Hardhead´s Reviews",
                    "HitPointsGaming",
                    "Hungry Gamer",
                    "Ines Juegos y más",
                    "Infinity Flux Comicx",
                    "JueGorrinos",
                    "Juegos de mesa 221B",
                    "Juegos de mesa en solitario",
                    "Jugamos en Mesa",
                    "Jugones Deluxe",
                    "La Mazmorra de Pacheco",
                    "La partida de los sábados",
                    "La Taberna de los Videojuegos",
                    "La zona lúdica de WulfricOMG",
                    "Loot \u0026 Fire",
                    "Los juegos de Ávatar",
                    "Maximus-society",
                    "Meepletopía",
                    "Meffy Games",
                    "Mi juego del mes",
                    "MiCabezaFriki",
                    "Mr. Flexx",
                    "MrPlayforlive",
                    "Nachere video \u0026 board gamer",
                    "OnTableTop Clips",
                    "Painting Fanatic",
					"Paquisto CustomBox",
                    "Pirate’s Parley Gaming!",
                    "Rapsoda Lúdico",
                    "Rescue Gamer",
                    "Ridlixcot linguafoeda acheronsis",
                    "Rolling Solo",
                    "SensaJuegos",
                    "So Play We All",
                    "Soloed Quest",
                    "Sulker",
                    "Talking Cardboard",
                    "Territorio Oca",
                    "The Discriminating Gamer",
                    "The Dungeon Dive",
                    "The Radikal Games",
                    "Unna",
                    "Viciados mesa",
                    "Walkyria Cómics",
                    "Yo tenía un juego",
                    "Zacatrus"
                ],
    "versions":  [
                     "Todas",
                     "Skull Tales",
                     "Skull Tales: A Toda Vela",
                     "Skull Tales: A Toda Vela (segunda edición)"
                 ]
};
